name: backpack
main: me.vlaggenstok.backpack.main.Main
version: 1.0
author: Ramine2001//Ramon//Vlaggenstok
commands:
  backpack:
    description: Main Command
    usage: /backpack , /backpack admin
    aliases: [bp]